"""
This type stub file was generated by pyright.
"""

from aiogram import Bot, Dispatcher

class Telegram:
    """
    A simple configurable Telegram bot, wrapped Aiogram.
    """
    __bot_token: str
    _bot: Bot
    _dp: Dispatcher
    def __init__(self, bot_token: str) -> None:
        ...
    
    def set_logging(self, level: int = ...):
        """
        Set the logging.
        """
        ...
    
    def get_bot(self) -> Bot:
        """
        Get the instanced bot.
        """
        ...
    
    def get_dp(self) -> Dispatcher:
        """
        Get the dispatcher of the instanced bot.
        """
        ...
    
    def polling(self) -> None:
        ...
    


