"""
This type stub file was generated by pyright.
"""

from asyncio.events import AbstractEventLoop
from asyncio.tasks import Task
from typing import Any
from aiogram import Bot, Dispatcher

class Telegram:
    """
    A simple configurable Telegram bot, wrapped Aiogram.
    """
    __bot_token: str
    _bot: Bot
    _dp: Dispatcher
    _loop: AbstractEventLoop
    def __init__(self, bot_token: str) -> None:
        ...
    
    def set_logging(self, level: int = ...):
        """
        Set the logging.
        """
        ...
    
    def get_bot(self) -> Bot:
        """
        Get the instanced bot.
        """
        ...
    
    def get_dp(self) -> Dispatcher:
        """
        Get the dispatcher of the instanced bot.
        """
        ...
    
    def start_polling(self) -> Task[Any]:
        """
        Start polling. Returns the created task.
        """
        ...
    
    def stop_polling(self) -> None:
        """
        Stop polling.
        """
        ...
    
    async def stop_bot(self) -> None:
        """
        Stop Bot.
        """
        ...
    


